# Generated by Django 3.0.4 on 2020-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('confirmed', models.IntegerField(verbose_name='confirmed_cases')),
                ('deaths', models.IntegerField(verbose_name='deaths')),
                ('recovered', models.IntegerField(verbose_name='recovered_cases')),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
