# Generated by Django 3.0.4 on 2020-03-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='time')),
                ('confirmed', models.IntegerField(verbose_name='confirmed_cases')),
                ('deaths', models.IntegerField(verbose_name='deaths')),
                ('recovered', models.IntegerField(verbose_name='recovered_cases')),
                ('new_cases', models.IntegerField(verbose_name='new_cases')),
                ('new_deaths', models.IntegerField(verbose_name='new_deaths')),
                ('serious', models.IntegerField(verbose_name='serious_cases')),
                ('mortality', models.FloatField(verbose_name='mortality')),
                ('active', models.IntegerField(verbose_name='active_cases')),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
