# Generated by Django 3.0.4 on 2020-03-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='serious',
            field=models.CharField(max_length=200, verbose_name='serious_cases'),
        ),
    ]
