# Generated by Django 3.0.4 on 2020-03-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200326_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='recovered',
            field=models.CharField(max_length=200, verbose_name='recovered_cases'),
        ),
    ]
