# Generated by Django 3.0.4 on 2020-03-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200326_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='active',
            field=models.CharField(max_length=200, verbose_name='active_cases'),
        ),
    ]
